### ISSUE TITLE
f.export_index() does not work properly after f.read()

### ISSUE THREAD

**Issue by pomidoroshev** [pauldmccarthy/indexed_gzip#18] opened 2019-05-09 15:12 UTC
Hi! I have a problem with exporting index after reading gzip file.

The problem is that exported file is almost empty (35 bytes) after just reading the entire source gzip without using `f.seek()`. So this index is just unusable.

Small script that reproduces this problem:

```python
import gzip
from indexed_gzip import IndexedGzipFile


def run():
    fname = 'foo.gz'
    fname_index = '%s.index' % fname

    create_test_file(fname)

    with IndexedGzipFile(fname) as f:
        f.read()
        f.export_index(fname_index)  # creates 35 bytes index file

    with IndexedGzipFile(fname) as f:
        f.import_index(fname_index)
        f.seek(2)  # fails


def create_test_file(fname):
    with gzip.open(fname, 'wt') as f:
        for _ in range(10000):
            f.write('foo\n')


if __name__ == '__main__':
    run()
```

But if I put `f.seek(f.tell() - 1)` right before `f.export_index()`, everything works great.

Is it supposed to work like that or just a bug?

**Comment by pauldmccarthy** [comment] 2019-05-10 08:28
Hey @pomidoroshev this looks like a bug - I'll take a look as soon as I can..

**Comment by pauldmccarthy** [comment] 2019-05-13 09:36
HI @pomidoroshev, the crux of the problem is that your test file is too small! `indexed_gzip` is designed to work with much larger files - it creates an index point for every 4MB of compressed data. But your compressed file is only 94 bytes compressed, 40k bytes uncompressed.

In your test case (thanks for providing that, btw), the `.index` file generated by `export_index` is valid - it just doesn't contain any index points. 

The `import_index` function does, however, crash when it's given an `.index` file which contains 0 index points - I'll make sure to fix this.

When you add the call to `f.seek(f.tell() - 1)`, a seek point is forcibly created at the beginning of the file, something which does not necessarily happen when you just call `read`. This means that the resulting `.index` file can be read by the buggy `import_index`. I'm not sure if I will change this behaviour - will have to look into it a bit more closely.

**Comment by pomidoroshev** [comment] 2019-05-14 09:19
Hi Paul,

> the crux of the problem is that your test file is too small! 

Oh, I see. My tool works with large gzip logs, and it creates another index by row date. I decided to read file line by line and export index at the end of the process, assuming this always works:

https://github.com/pauldmccarthy/indexed_gzip/blob/49c8b8e76132381e870a926f764cda3275fd19ce/indexed_gzip/indexed_gzip.pyx#L147-L148

But my test suite failed, because of small test files.

> When you add the call to `f.seek(f.tell() - 1)`, a seek point is forcibly created at the beginning of the file

You mean, at **the end** of the file? In my case `f.tell() - 1` is 39999, not 0.

> which does not necessarily happen when you just call `read`.

Can you correct the docstring about `auto_build` then?

> I'm not sure if I will change this behaviour

Ok, I'll stay with `f.seek()` workaround.

**Comment by pauldmccarthy** [comment] 2019-05-14 10:49
After digging deeper, and reminding myself how the code works, I realised that you should not rely on the `read` method to build the index - it will only get built when you `seek`, regardless of the vaue of `auto_build`. I'll update the docs to explain this.

But, regardless, if you want to pre-generate an index, the neatest way is probably via the `build_full_index` method, e.g.:

```python
fobj = igzip.IndexedGzipFile('file.gz')
fobj.build_full_index()
fobj.export_index('file.gz.index')
```

The bug in `import_index` has been fixed in #19, which I will merge in today(along with the doc updates) ..

**Comment by pomidoroshev** [comment] 2019-05-14 11:47
> the neatest way is probably via the build_full_index method

Yes, I used it before. But then I decided to build gzip index and my own date index in parallel during line-by-line reading.

**Comment by pauldmccarthy** [comment] 2019-05-14 11:51
Right, fair enough.  So I guess you will need to stick with `seek`/`read` pairs for the time being.

It's been a while since I wrote the relevant code (and it's quite complicated), so I'm still not sure why I'm not building the index on `read`. I will look into this when I get a chance, to see if I can change this behaviour, although it won't be today.

**Comment by pomidoroshev** [comment] 2019-05-14 13:04
It's ok, indexed_gzip is still the best, thank you!

**Closed** 2019-05-14 17:18 UTC
